###
# @name health
POST {{SERVICE_BASE_URL}}/health

###
# @name me
GET {{SERVICE_BASE_URL}}/auth/test
AUTHORIZATION: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zQ2N1U3l6cVlZejdMcGlwVWFRY0l0R2RkckgiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEiLCJleHAiOjE3NzY3MDQ1MzgsImZ2YSI6WzIxLC0xXSwiaWF0IjoxNzc2NzA0NDc4LCJpc3MiOiJodHRwczovL3ByZXNlbnQtdGVycmllci00NC5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NzY3MDQ0NjgsInNpZCI6InNlc3NfM0NkNmVWWFlkOWtmeXd3S3RoSmdtbTAzWTA2Iiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zQ2Q2ZVVmcFJGaGhERGZucTBUY2ttbU5xNmkiLCJ2IjoyfQ.nZsV_J2okIk9wi5yHt3IIswMn-rXefuYaijbs3nzdPNEG1-3f5MLMLxUGuzJ36DmZeRYb3pdktMY_UjsXah76XaZp8M1SDzZ9aCAC8lBtQa_h-gX2nhR_ZB3hrsbcnTVIvNgXXXw_IOSRjkw8i8auUjexqdG-oe0IzwARfBgqQxk1ATRWm1SPHtt6kuN7KuTRxk2fijiZEvaI2hH9BTMbV342GQFJhEGRTBV7t-J4xA-Wxx7zK-142N6yWZ5bcPCN67VJn7g_mzIlQ62qQt9XvwBxIjDV0QJ7Q8IOG9jz-lm6lh7KV8anMpZvzQehavGurhQsrfac-L7Y9fgP1N_vA
